import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { ArrowLeft, ArrowRight, ArrowUpRight, BookOpen, Check, ChevronDown, CircleHelp, Crosshair, Crown, ExternalLink, Eye, Flag, Globe2, Layers3, LoaderCircle, Maximize2, Minus, Orbit, Plus, Radio, RotateCcw, Search, Settings2, Shield, Swords, Target, X, Zap } from 'lucide-react';
import type { Card, Deck, GameAction, GameView, Player, PromptButton } from './types';

type Source = { title?: string; name?: string; url: string; description?: string; kind?: string };
type Drawer = 'rules' | 'sources' | 'settings' | null;
const SESSION_KEY = 'swu-command-session';
const SESSION_TOKEN_PREFIX = 'swu-command-state:';
const sessionTokens = new Map<string, string>();
const PREFERENCES_KEY = 'swu-command-preferences';
const DIFFICULTIES = [{ id: 'easy', label: 'Kadet', detail: 'Prvi koraci i opuštena partija.' }, { id: 'normal', label: 'Zapovjednik', detail: 'Procjenjuje tempo, prijetnje i vrijednost karata.' }, { id: 'hard', label: 'Veliki admiral', detail: 'Prioriteti borbe, sinergije i planiranje resursa.' }];
const DEFAULT_SOURCES: Source[] = [
  { title: 'Službena pravila i errata', url: 'https://starwarsunlimited.com/how-to-play', description: 'Fantasy Flight Games · referentna pravila' },
  { title: 'SWUDB', url: 'https://swudb.com', description: 'Baza karata i javni API' },
  { title: 'Forceteki / Karabast', url: 'https://github.com/SWU-Karabast/forceteki', description: 'Otvoreni sustav pravila i skripte karata' },
  { title: 'Reddit · r/starwarsunlimited', url: 'https://www.reddit.com/r/starwarsunlimited/', description: 'Rasprave o kartama i situacijama u igri' },
  { title: 'BoardGameGeek', url: 'https://boardgamegeek.com/boardgame/393040/star-wars-unlimited', description: 'Pitanja o pravilima i rasprave zajednice' },
];

function storedValue(key: string): string {
  try { return localStorage.getItem(key) || ''; } catch { return ''; }
}
function sessionToken(id: string): string {
  return sessionTokens.get(id) || storedValue(`${SESSION_TOKEN_PREFIX}${id}`) || '';
}
function rememberGame(view: GameView) {
  if (view.sessionToken) {
    sessionTokens.set(view.id, view.sessionToken);
    try { localStorage.setItem(`${SESSION_TOKEN_PREFIX}${view.id}`, view.sessionToken); } catch { /* The current tab can continue when storage is unavailable. */ }
  }
  try { localStorage.setItem(SESSION_KEY, view.id); } catch { /* Saving between visits may be disabled by the browser. */ }
}
function forgetGame(id: string) {
  sessionTokens.delete(id);
  try { localStorage.removeItem(`${SESSION_TOKEN_PREFIX}${id}`); if (localStorage.getItem(SESSION_KEY) === id) localStorage.removeItem(SESSION_KEY); } catch { /* Storage can be unavailable. */ }
}
async function api<T>(path: string, body?: unknown, requestMethod?: string): Promise<T> {
  let method = requestMethod || (body === undefined ? 'GET' : 'POST');
  const gameId = path.match(/^\/api\/games\/([^/]+)(?:\/(?:actions|bot|state))?$/)?.[1];
  if (gameId) {
    // Checkpoints can grow beyond HTTP header limits during a long game.
    if (method === 'GET') { path += '/state'; method = 'POST'; }
    body = { ...(body && typeof body === 'object' ? body : {}), sessionToken: sessionToken(decodeURIComponent(gameId)) };
  }
  const response = await fetch(path, { method, headers: { 'Content-Type': 'application/json' }, ...(body !== undefined ? { body: JSON.stringify(body) } : {}) });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw Object.assign(new Error(data.error || data.message || `Poslužitelj nije dostupan (${response.status}).`), { status: response.status });
  return data as T;
}
function preference(): { deckId?: string; opponentDeckId?: string; difficulty?: string } {
  try { return JSON.parse(localStorage.getItem(PREFERENCES_KEY) || '{}'); } catch { return {}; }
}
function imageUrl(card?: Partial<Card>): string | undefined {
  if (card?.image) return card.image;
  if (card?.code) { const [set, number] = card.code.split('_'); return `https://cdn.swu-db.com/images/cards/${set?.toUpperCase()}/${number}.png`; }
  return undefined;
}
function translate(text?: string): string {
  if (!text) return '';
  const exact: Record<string, string> = { 'Pass': 'Preskoči akciju', 'Claim Initiative': 'Preuzmi inicijativu', 'Claim initiative': 'Preuzmi inicijativu', 'Take initiative': 'Preuzmi inicijativu', 'Done': 'Potvrdi odabir', 'Cancel': 'Odustani', 'Yes': 'Da', 'No': 'Ne', 'Keep': 'Zadrži ruku', 'Keep hand': 'Zadrži ruku', 'Mulligan': 'Nova početna ruka', 'Choose an action': 'Odaberi svoju sljedeću akciju', 'Select an action': 'Odaberi svoju sljedeću akciju', 'Choose a card to resource': 'Odaberi kartu za resurs', 'Choose 2 cards to resource': 'Odaberi 2 karte za početne resurse', 'Pass priority': 'Prepusti akciju', 'Attack': 'Napadni', 'Play': 'Odigraj', 'Deploy': 'Rasporedi vođu', 'No target': 'Bez cilja', 'Pass for the phase': 'Preskoči do kraja faze', 'Yourself': 'Ja', 'Opponent': 'Protivnik', 'You won the flip. Choose the player to start with initiative:': 'Odaberi tko počinje s inicijativom.', 'choose initiative player': 'Početna inicijativa', 'Choose whether to mulligan or keep your hand': 'Zadrži početnu ruku ili izvuci novu.', 'Select 2 cards to resource': 'Odaberi 2 karte za početne resurse.', 'Select 1 card to resource': 'Odaberi kartu za novi resurs.', 'Confirm Resources': 'Potvrdi resurse', 'Skip Resourcing': 'Preskoči resurs', 'Resource Step': 'Odabir resursa', 'Choose an ability:': 'Odaberi sposobnost:', 'Waiting for opponent to take an action or pass': 'Protivnik odabire sljedeću akciju.', 'Waiting for opponent to choose whether to mulligan': 'Protivnik odlučuje o početnoj ruci.', 'Waiting for opponent to choose cards to resource': 'Protivnik odabire resurse.' };
  return exact[text] || text;
}
function phaseName(phase?: string) { return ({ setup: 'Priprema', action: 'Akcijska faza', regroup: 'Regrupiranje', 'actionPhase': 'Akcijska faza', 'regroupPhase': 'Regrupiranje' } as Record<string, string>)[phase || ''] || phase || 'Priprema'; }
function IconButton({ children, label, onClick, className = '', disabled }: { children: ReactNode; label: string; onClick: () => void; className?: string; disabled?: boolean }) { return <button type="button" className={`icon-button ${className}`} onClick={onClick} aria-label={label} title={label} disabled={disabled}>{children}</button>; }
function CardImage({ card, className = '', decorative = false }: { card?: Partial<Card>; className?: string; decorative?: boolean }) {
  const [failed, setFailed] = useState(false); const url = imageUrl(card);
  useEffect(() => setFailed(false), [url]);
  return url && !failed ? <img src={url} alt={decorative ? '' : card?.name || 'Karta'} className={className} loading="lazy" onError={() => setFailed(true)} /> : <div className={`card-art-fallback ${className}`}><Orbit size={36} /><span>{card?.name || 'STAR WARS'}</span></div>;
}
function Brand({ small = false }: { small?: boolean }) { return <div className={`brand ${small ? 'brand-small' : ''}`}><div className="brand-emblem"><Orbit strokeWidth={1.3} /></div><div className="brand-wordmark"><span>STAR WARS</span><strong>UNLIMITED</strong></div><span className="brand-divider" /><span className="brand-app">COMMAND<span>SOLO PLAY SYSTEM</span></span></div>; }
function AspectDots({ aspects = [] }: { aspects?: string[] }) { return <div className="aspects" aria-label={aspects.join(', ')}>{aspects.map((aspect, i) => <span key={`${aspect}-${i}`} className={`aspect aspect-${aspect.toLowerCase()}`} title={aspect} />)}</div>; }
function Modal({ title, children, close, wide = false }: { title: string; children: ReactNode; close: () => void; wide?: boolean }) {
  const dialog = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const previous = document.activeElement as HTMLElement | null;
    const onKey = (event: KeyboardEvent) => {
      if (event.key === 'Escape') close();
      if (event.key === 'Tab') {
        const nodes = dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a,input,select,[tabindex="0"]');
        if (!nodes?.length) return;
        const first = nodes[0], last = nodes[nodes.length - 1];
        if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); }
        else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); }
      }
    };
    document.addEventListener('keydown', onKey); dialog.current?.querySelector<HTMLElement>('button')?.focus();
    const old = document.body.style.overflow; document.body.style.overflow = 'hidden';
    return () => { document.removeEventListener('keydown', onKey); document.body.style.overflow = old; previous?.focus(); };
  }, [close]);
  return <div className="modal-scrim" onMouseDown={e => { if (e.target === e.currentTarget) close(); }}><div ref={dialog} className={`modal ${wide ? 'modal-wide' : ''}`} role="dialog" aria-modal="true" aria-label={title}><header className="modal-header"><div><span className="eyebrow">COMMAND DATABASE</span><h2>{title}</h2></div><IconButton label="Zatvori" onClick={close}><X size={20} /></IconButton></header>{children}</div></div>;
}

export default function App() {
  const prefs = useMemo(preference, []);
  const [decks, setDecks] = useState<Deck[]>([]); const [sources, setSources] = useState<Source[]>(DEFAULT_SOURCES);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [deckId, setDeckId] = useState(prefs.deckId || ''); const [opponentDeckId, setOpponentDeckId] = useState(prefs.opponentDeckId || '');
  const [difficulty, setDifficulty] = useState(prefs.difficulty || 'normal'); const [game, setGame] = useState<GameView | null>(null);
  const [savedSession, setSavedSession] = useState(() => storedValue(SESSION_KEY));
  const requestPending = useRef(false);
  const [drawer, setDrawer] = useState<Drawer>(null); const [inspect, setInspect] = useState<Card | null>(null);
  const [inspectDeck, setInspectDeck] = useState<Deck | null>(null); const [rulesVersion, setRulesVersion] = useState('');
  const [slot, setSlot] = useState<'human' | 'bot'>('human'); const [setFilter, setSetFilter] = useState('all'); const [search, setSearch] = useState('');
  const [showLog, setShowLog] = useState(true); const [finishedDismissed, setFinishedDismissed] = useState(false);
  const [compact, setCompact] = useState(false); const [reverseCard, setReverseCard] = useState(false);
  useEffect(() => setReverseCard(false), [inspect?.uuid, inspect?.id]);
  const selected = decks.find(deck => deck.id === deckId); const opponent = decks.find(deck => deck.id === opponentDeckId);
  const closeInspect = useCallback(() => setInspect(null), []); const closeDeck = useCallback(() => setInspectDeck(null), []); const closeDrawer = useCallback(() => setDrawer(null), []);
  const loadDecks = useCallback(async () => {
    setLoading(true); setError('');
    try {
      const data = await api<{ decks: Deck[]; sources?: Source[]; rulesVersion?: string } | Deck[]>('/api/decks');
      const list = (Array.isArray(data) ? data : data.decks).map(deck => ({ ...deck, aspects: deck.aspects || [...(deck.leader?.aspects || []), ...(deck.base?.aspects || [])] }));
      setDecks(list); setDeckId(old => list.some(d => d.id === old) ? old : list[0]?.id || ''); setOpponentDeckId(old => list.some(d => d.id === old) ? old : list[1]?.id || list[0]?.id || '');
      if (!Array.isArray(data)) { if (data.sources?.length) setSources(data.sources); setRulesVersion(data.rulesVersion || ''); }
    } catch (e) { setError((e as Error).message); } finally { setLoading(false); }
  }, []);
  useEffect(() => { void loadDecks(); }, [loadDecks]);
  useEffect(() => { try { localStorage.setItem(PREFERENCES_KEY, JSON.stringify({ deckId, opponentDeckId, difficulty })); } catch { /* Preferences are optional. */ } }, [deckId, opponentDeckId, difficulty]);
  const acceptGame = (view: GameView) => { rememberGame(view); setGame(view); setSavedSession(view.id); };
  const startGame = async () => {
    if (!deckId || !opponentDeckId || requestPending.current) return;
    requestPending.current = true;
    setBusy(true); setError(''); setFinishedDismissed(false);
    try { const previous = game?.id || savedSession; const next = await api<GameView>('/api/games', { deckId, opponentDeckId, difficulty }); acceptGame(next); if (previous && previous !== next.id) void api(`/api/games/${encodeURIComponent(previous)}`, {}, 'DELETE').catch(() => {}).finally(() => forgetGame(previous)); window.scrollTo({ top: 0 }); }
    catch (e) { setError((e as Error).message); } finally { requestPending.current = false; setBusy(false); }
  };
  const resume = async () => {
    if (requestPending.current) return;
    requestPending.current = true;
    setBusy(true); setError('');
    try { acceptGame(await api<GameView>(`/api/games/${encodeURIComponent(savedSession)}`)); }
    catch (e) { setError(`Spremljena sesija nije dostupna. ${(e as Error).message}`); if ([400, 401, 403, 404, 410].includes((e as Error & { status?: number }).status || 0)) { forgetGame(savedSession); setSavedSession(''); } }
    finally { requestPending.current = false; setBusy(false); }
  };
  const act = async (action: GameAction) => {
    if (!game || requestPending.current) return;
    requestPending.current = true;
    setBusy(true); setError('');
    try { acceptGame(await api<GameView>(`/api/games/${encodeURIComponent(game.id)}/actions`, { ...action, version: game.version })); }
    catch (e) { setError((e as Error).message); if ((e as Error & { status?: number }).status === 409) { try { acceptGame(await api<GameView>(`/api/games/${encodeURIComponent(game.id)}`)); } catch { /* Keep current table visible if reconnect fails. */ } } } finally { requestPending.current = false; setBusy(false); }
  };
  const continueBot = async () => {
    if (!game || requestPending.current) return; requestPending.current = true; setBusy(true); setError('');
    try { acceptGame(await api<GameView>(`/api/games/${encodeURIComponent(game.id)}/bot`, {})); }
    catch (e) { setError((e as Error).message); } finally { requestPending.current = false; setBusy(false); }
  };
  const sets = [...new Set(decks.map(deck => deck.set))];
  const filtered = decks.filter(deck => (setFilter === 'all' || deck.set === setFilter) && `${deck.name} ${deck.leader?.name} ${deck.setName || ''}`.toLowerCase().includes(search.toLowerCase()));
  return <div className={`app ${game ? 'in-game' : ''} ${compact ? 'compact' : ''}`}>
    <header className="site-header"><button className="brand-button" onClick={() => setGame(null)} aria-label="Povratak u zapovjedništvo"><Brand /></button><nav aria-label="Glavna navigacija"><button className={!game ? 'nav-link active' : 'nav-link'} onClick={() => setGame(null)}><Layers3 size={15} /><span>Zapovjedništvo</span></button><button className="nav-link" onClick={() => setDrawer('rules')}><BookOpen size={15} /><span>Pravila igre</span></button><button className="nav-link" onClick={() => setDrawer('sources')}><Globe2 size={15} /><span>Izvori</span></button></nav><div className="header-right"><span className="system-status"><i /> SUSTAV AKTIVAN</span><IconButton label="Postavke" onClick={() => setDrawer('settings')}><Settings2 size={18} /></IconButton></div></header>
    {error && <div className="error-banner" role="alert"><CircleHelp size={18} /><span>{error}</span><button onClick={() => setError('')} aria-label="Zatvori obavijest"><X size={18} /></button></div>}
    {game ? <GameTable game={game} busy={busy} act={act} inspect={setInspect} showLog={showLog} setShowLog={setShowLog} restart={startGame} continueBot={continueBot} back={() => setGame(null)} /> : <main className="lobby">
      <section className="hero"><div className="hero-copy"><div className="eyebrow hero-eyebrow"><span className="signal-line" /> TAKTIČKI SIMULATOR · 1 NA 1</div><h1>GALAKSIJA ČEKA<br />TVOG <span>ZAPOVJEDNIKA.</span></h1><p>Izaberi svoju stranu. Okupi flotu.<br />Odmjeri snage s AI protivnikom u igri Star Wars: Unlimited.</p><div className="hero-tags"><span><Swords size={15} /> Igra protiv AI-ja</span><span><Zap size={15} /> Automatizirana pravila</span><span><Layers3 size={15} /> Početni špilovi</span></div>{savedSession && <button className="resume-button" onClick={resume} disabled={busy}><Radio size={16} /> Nastavi posljednju partiju <ArrowUpRight size={16} /></button>}</div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="orbit-crosshair" /><span className="sector-label">SECTOR 07 / OUTER RIM</span><div className="hero-card hero-card-back"><CardImage card={opponent?.leader} decorative /></div><div className="hero-card hero-card-front"><CardImage card={selected?.leader} decorative /></div><div className="hero-art-label"><span className="signal-dot" /> SUKOB JE NEIZBJEŽAN<span>ODLUKA JE TVOJA.</span></div></div></section>
      <section className="mission-panel" aria-label="Postavljanje partije"><div className="mission-heading"><span className="eyebrow">01 / PRIPREMA MISIJE</span><span>{selected?.format?.includes('Intro') || opponent?.format?.includes('Intro') ? 'INTRO BATTLE · 20 HP' : 'PREMIER · 1V1'}</span></div><div className="mission-content"><button className={`combatant-select ${slot === 'human' ? 'selected' : ''}`} onClick={() => setSlot('human')}><div className="combatant-portrait friendly"><CardImage card={selected?.leader} decorative /></div><div><span className="eyebrow"><span className="friendly-dot" /> TVOJ ŠPIL</span><h3>{selected?.leader?.name || 'Odaberi zapovjednika'}</h3><p>{selected?.name || 'Učitavanje arhive…'}</p></div><ChevronDown size={16} /></button><div className="versus"><span /><Swords size={23} /><span /></div><button className={`combatant-select enemy ${slot === 'bot' ? 'selected' : ''}`} onClick={() => setSlot('bot')}><div className="combatant-portrait"><CardImage card={opponent?.leader} decorative /></div><div><span className="eyebrow"><span className="enemy-dot" /> AI PROTIVNIK</span><h3>{opponent?.leader?.name || 'Odaberi protivnika'}</h3><p>{opponent?.name || 'Učitavanje arhive…'}</p></div><ChevronDown size={16} /></button><div className="mission-launch"><label htmlFor="difficulty" className="eyebrow">RAZINA PROTIVNIKA</label><div className="select-wrap"><select id="difficulty" value={difficulty} onChange={event => setDifficulty(event.target.value)}>{DIFFICULTIES.map(item => <option value={item.id} key={item.id}>{item.label}</option>)}</select><ChevronDown size={14} /></div><button className="primary-button launch-button" onClick={startGame} disabled={busy || loading || !decks.length || selected?.supported === false || opponent?.supported === false}>{busy ? <LoaderCircle className="spin" size={19} /> : <Crosshair size={19} />}{busy ? 'Priprema bojišta…' : 'Započni bitku'}{!busy && <ArrowRight size={18} />}</button></div></div></section>
      <section className="deck-library" aria-labelledby="library-title"><div className="section-heading"><div><span className="eyebrow">02 / ARHIVA ŠPILOVA</span><h2 id="library-title">IZABERI SVOJU STRANU<span>{decks.length.toString().padStart(2, '0')}</span></h2></div><div className={`selection-indicator ${slot === 'bot' ? 'enemy-text' : ''}`}><span className="signal-dot" /> Biraš špil za: <strong>{slot === 'human' ? 'sebe' : 'AI protivnika'}</strong></div></div><div className="library-toolbar"><div className="set-filters" aria-label="Filtriraj set"><button className={setFilter === 'all' ? 'active' : ''} onClick={() => setSetFilter('all')}>Svi špilovi</button>{sets.map(set => <button className={setFilter === set ? 'active' : ''} key={set} onClick={() => setSetFilter(set)}>{set}</button>)}</div><label className="search-field"><Search size={16} /><input aria-label="Pretraži špilove" placeholder="Pronađi zapovjednika…" value={search} onChange={e => setSearch(e.target.value)} /></label></div>
        {loading ? <div className="loading-state"><LoaderCircle className="spin" size={28} /><p>Pristup galaktičkoj arhivi…</p></div> : decks.length === 0 ? <div className="empty-state"><Radio size={32} /><h3>Arhiva trenutačno nije dostupna</h3><p>Provjeri vezu s poslužiteljem i pokušaj ponovo.</p><button className="secondary-button" onClick={loadDecks}><RotateCcw size={16} /> Pokušaj ponovo</button></div> : filtered.length === 0 ? <div className="empty-state"><Search size={28} /><h3>Nema pronađenih špilova</h3><button className="text-button" onClick={() => { setSearch(''); setSetFilter('all'); }}>Očisti filtere</button></div> : <div className="deck-grid">{filtered.map((deck, i) => <DeckTile key={deck.id} deck={deck} index={i} playerSelected={deck.id === deckId} botSelected={deck.id === opponentDeckId} activeSelected={deck.id === (slot === 'human' ? deckId : opponentDeckId)} select={() => slot === 'human' ? setDeckId(deck.id) : setOpponentDeckId(deck.id)} inspect={() => setInspectDeck(deck)} />)}</div>}
      </section><section className="how-it-works"><div><span className="eyebrow">TAKTIČKA PREDNOST</span><h2>Jedna akcija. Bezbroj mogućnosti.</h2><p>Igrajte naizmjence, razvijajte resurse i napadajte u dvije arene. Uništi protivničku bazu prije nego što padne tvoja.</p></div><div className="how-item"><span>01</span><Crosshair /><h3>Preuzmi inicijativu</h3><p>Prvi potez sljedeće runde može promijeniti sve.</p></div><div className="how-item"><span>02</span><Orbit /><h3>Vladaj objema arenama</h3><p>Poveži kopnene snage i svemirsku flotu.</p></div><div className="how-item"><span>03</span><Crown /><h3>Rasporedi vođu</h3><p>U pravom trenutku pošalji zapovjednika u borbu.</p></div></section>
    </main>}
    {!game && <footer className="site-footer"><Brand small /><p>Neslužbeni projekt zajednice. Star Wars i pripadajući sadržaj © Lucasfilm / Fantasy Flight Games.</p><button className="text-button" onClick={() => setDrawer('sources')}>Podaci i izvori <ArrowUpRight size={14} /></button></footer>}
    {drawer && <Modal title={drawer === 'rules' ? 'Priručnik zapovjednika' : drawer === 'sources' ? 'Izvori i podaci' : 'Postavke sustava'} close={closeDrawer} wide={drawer === 'rules'}>{drawer === 'rules' ? <RulesContent openSources={() => setDrawer('sources')} version={rulesVersion} /> : drawer === 'sources' ? <div className="modal-body sources-body"><p className="muted">Službena pravila imaju prednost pred tumačenjima zajednice. Izvori zajednice služe za pojašnjenja specifičnih situacija.</p>{sources.map((source, i) => <a key={i} className="source-link" href={source.url} target="_blank" rel="noreferrer"><span><strong>{source.title || source.name || new URL(source.url).hostname}</strong><small>{source.description || source.kind || source.url}</small></span><ExternalLink size={17} /></a>)}<div className="notice"><CircleHelp size={18} /><span>Projekt nije službeno povezan s Lucasfilmom, FFG-om ili Karabastom. Katalog prikazuje dostupnost skripti; posebna ograničenja navedena su uz špil.</span></div></div> : <div className="modal-body"><div className="setting-block"><h3>Razina AI protivnika</h3><p className="muted">Promjena vrijedi za sljedeću partiju.</p><div className="difficulty-options">{DIFFICULTIES.map(item => <button key={item.id} className={difficulty === item.id ? 'selected' : ''} onClick={() => setDifficulty(item.id)}><span><strong>{item.label}</strong><small>{item.detail}</small></span>{difficulty === item.id && <Check size={18} />}</button>)}</div></div><div className="setting-row"><span><strong>Kompaktne karte</strong><small>Više prostora za velike arene.</small></span><button className={`toggle ${compact ? 'on' : ''}`} role="switch" aria-checked={compact} aria-label="Kompaktne karte" onClick={() => setCompact(!compact)}><i /></button></div><div className="setting-row"><span><strong>Dnevnik partije</strong><small>Prikaži poteze uz bojište.</small></span><button className={`toggle ${showLog ? 'on' : ''}`} role="switch" aria-checked={showLog} aria-label="Dnevnik partije" onClick={() => setShowLog(!showLog)}><i /></button></div><div className="notice"><Radio size={17} /><span>Partija se šifrirano pamti u ovom pregledniku do šest sati od početka. Možeš je nastaviti nakon osvježavanja stranice. Koristi jednu karticu preglednika po partiji.</span></div></div>}</Modal>}
    {inspect && <Modal title={inspect.name || 'Detalji karte'} close={closeInspect} wide><div className="card-detail"><div className={`card-detail-art ${inspect.type?.includes('leader') || inspect.type?.includes('base') ? 'landscape' : ''}`}><CardImage card={reverseCard && inspect.backImage ? { ...inspect, image: inspect.deployed ? inspect.frontImage || inspect.image : inspect.backImage } : inspect} />{inspect.backImage && <button className="secondary-button small-button reverse-card" onClick={() => setReverseCard(!reverseCard)}><RotateCcw size={14} />{reverseCard ? 'Pokaži aktivnu stranu' : 'Okreni kartu'}</button>}</div><div className="card-detail-copy"><span className="eyebrow">{inspect.code || inspect.type || 'GALAKTIČKA ARHIVA'}</span><h2>{inspect.name}</h2>{inspect.subtitle && <h3>{inspect.subtitle}</h3>}<div className="card-detail-stats">{inspect.cost != null && <span><Zap size={15} /> {inspect.cost} <small>CIJENA</small></span>}{inspect.power != null && <span><Swords size={15} /> {inspect.power} <small>SNAGA</small></span>}{inspect.hp != null && <span><Shield size={15} /> {inspect.remainingHp ?? inspect.hp} / {inspect.hp} <small>ŽIVOT</small></span>}</div>{inspect.keywords?.length ? <div className="keyword-list">{inspect.keywords.map((keyword, i) => <span key={i}>{typeof keyword === 'string' ? keyword : `${keyword.name}${keyword.value != null ? ` ${keyword.value}` : ''}`}</span>)}</div> : null}<p className="rules-text">{(reverseCard ? inspect.deployed ? inspect.frontText : inspect.deployText : inspect.text) || 'Tekst sposobnosti prikazan je na slici karte.'}</p>{inspect.epicAction && <p className="rules-text"><strong>Epic Action</strong><br />{inspect.epicAction}</p>}{inspect.traits?.length ? <p className="traits">{inspect.traits.join(' · ')}</p> : null}{inspect.exhausted && <p className="status-note"><RotateCcw size={14} /> Iscrpljena karta</p>}{inspect.upgrades?.length ? <div className="attached-cards"><h4>Nadogradnje</h4>{inspect.upgrades.map(card => <button key={card.uuid} onClick={() => setInspect(card)}>{card.name}<Eye size={14} /></button>)}</div> : null}{inspect.captured?.length ? <div className="attached-cards"><h4>Zarobljene jedinice</h4>{inspect.captured.map(card => <button key={card.uuid} onClick={() => setInspect(card)}>{card.name}<Eye size={14} /></button>)}</div> : null}{inspect.unimplemented && <div className="notice">Skripta ove karte nije dostupna u ugrađenom sustavu.</div>}</div></div></Modal>}
    {inspectDeck && <Modal title={inspectDeck.name} close={closeDeck} wide><div className="deck-detail-header"><CardImage card={inspectDeck.leader} /><div><span className="eyebrow">{inspectDeck.setName || inspectDeck.set}</span><h2>{inspectDeck.leader.name}</h2><p>{inspectDeck.description || 'Službeni unaprijed složen špil.'}</p><AspectDots aspects={inspectDeck.aspects} />{inspectDeck.supported === false && <div className="notice">Špil sadrži karte bez dostupnih skripti i trenutačno nije moguće započeti partiju s njim.</div>}</div></div>{inspectDeck.cards?.length ? <div className="deck-list">{inspectDeck.cards.map(({ card, count }, i) => <button key={`${card.id}-${i}`} onClick={() => { setInspectDeck(null); setInspect(card); }}><span className="deck-list-quantity">{count}×</span><span className="deck-list-name">{card.name || card.code}</span><span className="deck-list-cost">{card.cost ?? '—'}</span><Eye size={14} /></button>)}</div> : <p className="modal-body muted">Sastav ovog špila dostupan je u uvezenim podacima na poslužitelju.</p>}<div className="modal-actions"><button className="primary-button" onClick={() => { slot === 'human' ? setDeckId(inspectDeck.id) : setOpponentDeckId(inspectDeck.id); setInspectDeck(null); }}>Odaberi špil <ArrowRight size={17} /></button></div></Modal>}
    {game && game.winnerIds?.length > 0 && !finishedDismissed && <Modal title={game.winnerIds.length > 1 ? 'Neriješen ishod' : game.winnerIds.includes('human') ? 'Misija uspješno završena' : 'Bitka je završena'} close={() => setFinishedDismissed(true)}><div className="victory-content"><div className={`victory-symbol ${game.winnerIds.includes('human') ? 'won' : ''}`}>{game.winnerIds.includes('human') ? <Crown size={48} /> : <Shield size={48} />}</div><span className="eyebrow">RUNDA {game.round}</span><h2>{game.winnerIds.length > 1 ? 'RAVNOTEŽA U GALAKSIJI.' : game.winnerIds.includes('human') ? 'POBJEDA JE TVOJA.' : 'GALAKSIJA PAMTI HRABRE.'}</h2><p>{game.winnerIds.length > 1 ? 'Obje baze pale su istodobno. Partija je završila neriješeno.' : game.winnerIds.includes('human') ? 'Protivnička baza je pala. Odličan posao, zapovjedniče.' : 'Ovaj put protivnik je bio uspješniji. Novi plan, nova prilika.'}</p><button className="primary-button" onClick={startGame} disabled={busy}><RotateCcw size={17} /> Nova partija</button><button className="text-button" onClick={() => setFinishedDismissed(true)}>Pregledaj završno stanje <ArrowRight size={15} /></button></div></Modal>}
  </div>;
}

function DeckTile({ deck, index, playerSelected, botSelected, activeSelected, select, inspect }: { deck: Deck; index: number; playerSelected: boolean; botSelected: boolean; activeSelected: boolean; select: () => void; inspect: () => void }) {
  return <article className={`deck-tile ${activeSelected ? 'deck-selected' : ''} ${deck.supported === false ? 'deck-unsupported' : ''}`} style={{ '--tile-delay': `${Math.min(index, 12) * 35}ms` } as React.CSSProperties}><button className="deck-tile-main" onClick={select} aria-label={`Odaberi špil ${deck.name}`} aria-pressed={activeSelected}><div className="deck-art"><CardImage card={deck.leader} decorative /><span className="deck-set">{deck.set}</span><div className="deck-selection-badges">{playerSelected && <span className="your-deck"><Check size={10} /> TVOJ ŠPIL</span>}{botSelected && <span className="bot-deck"><Crosshair size={10} /> AI</span>}</div><span className="deck-art-index">{(index + 1).toString().padStart(2, '0')}</span></div><div className="deck-info"><div className="deck-faction"><span>{deck.format?.includes('Intro') ? 'INTRO BATTLE · 20 HP' : deck.product?.includes('Spotlight') ? 'SPOTLIGHT DECK' : 'STARTER DECK'}</span><AspectDots aspects={deck.aspects} /></div><h3>{deck.leader?.name || deck.name}</h3><p>{deck.leader?.subtitle || deck.name}</p></div></button><div className="deck-tile-footer"><span className={deck.supported === false ? 'unsupported-label' : ''}>{deck.supported === false ? 'Skripte nedostaju' : `${deck.count || deck.cards?.reduce((sum, row) => sum + row.count, 0) || 50} karata`}</span><button onClick={inspect}>Pregled špila <ArrowUpRight size={14} /></button></div></article>;
}

function GameTable({ game, busy, act, inspect, showLog, setShowLog, restart, continueBot, back }: { game: GameView; busy: boolean; act: (a: GameAction) => Promise<void>; inspect: (card: Card) => void; showLog: boolean; setShowLog: (show: boolean) => void; restart: () => Promise<void>; continueBot: () => Promise<void>; back: () => void }) {
  const human = game.players.human, bot = game.players.bot;
  const allCards = useMemo(() => { const flatten = (cards: Card[]): Card[] => cards.filter(Boolean).flatMap(card => [card, ...flatten(card.upgrades || []), ...flatten(card.captured || [])]); return Object.values(game.players).flatMap(player => flatten([player.base, ...(player.leaders || [player.leader]), ...player.hand, ...player.ground, ...player.space, ...player.resources, ...player.discard, ...(player.credits || []), ...(player.outsideTheGame || [])])); }, [game]);
  const [pile, setPile] = useState<{ title: string; cards: Card[] } | null>(null); const closePile = useCallback(() => setPile(null), []);
  const cardAction = (card: Card) => game.legalActions.find(a => a.type === 'card' && a.cardId === card.uuid);
  const handleCard = (card: Card) => { const action = cardAction(card); if (action) void act(action); else if (!card.hidden) inspect(card); };
  const currentReason = game.botReason || game.botThinking?.reason || game.ai?.reason || game.ai?.lastDecision?.reason || game.botHistory?.at(-1)?.reason;
  const ended = game.winnerIds?.length > 0;
  return <main className={`game-shell ${showLog ? '' : 'without-log'}`}><div className="game-topbar"><button className="text-button" onClick={back}><ArrowLeft size={15} /><span>Zapovjedništvo</span></button><div className="round-label"><span>RUNDA</span><strong>{String(game.round || 1).padStart(2, '0')}</strong><i /><span>{phaseName(game.phase)}</span></div><div className="game-tools"><span className="game-session">{game.id.slice(0, 8)}</span><IconButton label={showLog ? 'Sakrij dnevnik' : 'Prikaži dnevnik'} onClick={() => setShowLog(!showLog)}><Radio size={17} /></IconButton><IconButton label="Nova partija s istim špilovima" onClick={() => void restart()} disabled={busy}><RotateCcw size={17} /></IconButton></div></div>
    <div className="battle-layout"><div className="battlefield"><div className="commander-row opponent-row"><PlayerPanel player={bot} enemy inspect={inspect} cardAction={cardAction} onCard={handleCard} busy={busy} /><div className="opponent-hand" aria-label={`Protivnik ima ${bot.handCount} karata u ruci`}>{Array.from({ length: Math.min(bot.handCount, 9) }, (_, i) => <div className="card-back" key={i}><Orbit size={23} strokeWidth={1} /></div>)}<span>{bot.handCount} KARATA U RUCI</span></div><PilePanel player={bot} enemy open={setPile} /><Initiative game={game} player={bot} /></div>
    <div className="arenas"><Arena name="KOPNENA ARENA" kind="ground" enemyCards={bot.ground} friendlyCards={human.ground} cardAction={cardAction} onCard={handleCard} inspect={inspect} busy={busy} attackerId={game.prompt?.attackerId} /><Arena name="SVEMIRSKA ARENA" kind="space" enemyCards={bot.space} friendlyCards={human.space} cardAction={cardAction} onCard={handleCard} inspect={inspect} busy={busy} attackerId={game.prompt?.attackerId} /></div>
    <div className="commander-row friendly-row"><PlayerPanel player={human} inspect={inspect} cardAction={cardAction} onCard={handleCard} busy={busy} /><div className="resource-display"><span className="eyebrow">RASPOLOŽIVI RESURSI</span><div className="resource-count"><Zap size={20} /><strong>{human.readyResources}</strong><span>/ {human.resourceCount}</span></div><div className="resource-pips">{Array.from({ length: Math.min(human.resourceCount, 18) }, (_, i) => <i key={i} className={i < human.readyResources ? 'ready' : ''} />)}</div><button className="text-button" onClick={() => setPile({ title: 'Tvoji resursi', cards: human.resources })}>Pregled resursa <Eye size={13} /></button></div><PilePanel player={human} open={setPile} /><Initiative game={game} player={human} /></div>
    <TokenControls game={game} busy={busy} act={act} inspect={inspect} /><PromptPanel game={game} busy={busy} act={act} cards={allCards} inspect={inspect} />{game.warnings?.length ? <button className="secondary-button bot-recovery" disabled={busy} onClick={() => void continueBot()}><RotateCcw size={14} />Nastavi AI potez</button> : null}
    <section className="hand-section" aria-label="Tvoja ruka"><div className="hand-heading"><span className="eyebrow">TVOJA RUKA <b>{human.hand.length}</b></span><span><Eye size={12} /> Ikona povećala otvara detalje karte</span></div><div className="hand-cards">{human.hand.map((card, i) => <GameCard key={card.uuid || i} card={card} mode="hand" canAct={!!cardAction(card)} onClick={() => handleCard(card)} inspect={() => inspect(card)} busy={busy} />)}{!human.hand.length && <div className="empty-hand"><Layers3 size={20} /> Nemaš karata u ruci.</div>}</div></section>
    </div>{showLog && <aside className="command-sidebar"><div className="sidebar-title"><span className="eyebrow">TAKTIČKI CENTAR</span><Radio size={15} /></div><div className="ai-status"><div className="ai-icon"><Crosshair size={22} /></div><div><span className="eyebrow">AI PROTIVNIK</span><h3>{DIFFICULTIES.find(d => d.id === game.difficulty)?.label || 'Zapovjednik'}</h3></div><span className="signal-dot enemy-dot" /></div><div className="ai-reason"><span className="eyebrow">POSLJEDNJA PROCJENA</span><p>{currentReason || (busy ? 'Analiziram stanje bojišta…' : 'AI procjenjuje tempo, stanje baza, prijetnje i vrijednost razmjene jedinica.')}</p></div><div className="log-heading"><h3>Dnevnik bitke</h3><span>{game.log.length}</span></div><div className="game-log" role="log" aria-label="Dnevnik partije">{game.log.length ? [...game.log].reverse().map((entry, i) => <div className={`log-entry ${i === 0 ? 'latest' : ''}`} key={typeof entry === 'string' ? `${game.log.length - i}` : entry.id || `${game.log.length - i}`}><span className="log-marker" /><div><p>{typeof entry === 'string' ? entry : entry.message || entry.text || ''}</p>{typeof entry !== 'string' && entry.round != null && <span>RUNDA {entry.round}</span>}</div></div>) : <div className="log-empty">Čekamo prve naredbe.</div>}</div><div className="sidebar-footer"><Shield size={14} /><span>{ended ? 'Partija je završena' : 'Pravila provjerava sustav igre'}</span></div></aside>}</div>
    {pile && <Modal title={pile.title} close={closePile} wide><div className="pile-grid">{pile.cards.length ? pile.cards.map((card, i) => card.hidden ? <div className="hidden-pile-card" key={i}><Orbit /><span>Skrivena karta</span></div> : <GameCard key={card.uuid || i} card={card} mode="hand" canAct={!!cardAction(card)} onClick={() => { if (cardAction(card)) { handleCard(card); setPile(null); } else { setPile(null); inspect(card); } }} inspect={() => { setPile(null); inspect(card); }} busy={busy} />) : <div className="empty-state">Ova hrpa je prazna.</div>}</div></Modal>}
  </main>;
}

function PlayerPanel({ player, enemy = false, inspect, cardAction, onCard, busy }: { player: Player; enemy?: boolean; inspect: (card: Card) => void; cardAction: (c: Card) => GameAction | undefined; onCard: (card: Card) => void; busy: boolean }) {
  const base = player.base; const maximum = Number(base?.hp) || 30; const remaining = base?.remainingHp ?? maximum - (base?.damage || 0); const leader = player.leader || player.leaders?.[0];
  return <div className={`player-panel ${enemy ? 'enemy' : 'friendly'} ${player.active ? 'player-active' : ''}`}><div className="player-name"><span className={enemy ? 'enemy-dot' : 'friendly-dot'} /><span>{enemy ? 'AI PROTIVNIK' : 'TVOJA KOMANDA'}</span>{player.active && <small>NA POTEZU</small>}</div><div className="player-cards"><div className={`leader-mini ${leader?.exhausted ? 'is-exhausted' : ''} ${leader && cardAction(leader) ? 'is-legal' : ''}`}><button data-card-id={leader?.uuid} onClick={() => leader && onCard(leader)} disabled={busy || !leader} aria-label={leader?.name || 'Vođa'}><CardImage card={leader} decorative /><span>{leader?.name || 'Vođa'}</span></button>{leader && <IconButton label={`Detalji: ${leader.name}`} onClick={() => inspect(leader)}><Maximize2 size={11} /></IconButton>}</div><button data-card-id={base?.uuid} className={`base-panel ${base && cardAction(base) ? 'is-legal' : ''}`} onClick={() => base && onCard(base)} disabled={busy || !base} aria-label={`${base?.name || 'Baza'}, život ${remaining} od ${maximum}`}><div><Shield size={14} /><span>{base?.name || 'BAZA'}</span></div><p><strong>{remaining}</strong><span>/ {maximum}</span></p><div className="health-track"><i style={{ width: `${Math.max(0, Math.min(100, remaining / maximum * 100))}%` }} /></div></button></div></div>;
}
function PilePanel({ player, enemy = false, open }: { player: Player; enemy?: boolean; open: (p: { title: string; cards: Card[] }) => void }) { return <div className="pile-panel"><div className="pile-stat"><Layers3 size={19} /><strong>{player.deckCount}</strong><span>ŠPIL</span></div><button className="pile-stat" onClick={() => open({ title: enemy ? 'Protivnikova odbačena hrpa' : 'Tvoja odbačena hrpa', cards: player.discard })}><Layers3 size={19} /><strong>{player.discard.length}</strong><span>ODBAČENO</span></button>{enemy && <div className="pile-stat resource-stat"><Zap size={18} /><strong>{player.readyResources}<small>/{player.resourceCount}</small></strong><span>RESURSI</span></div>}</div>; }
function Initiative({ game, player }: { game: GameView; player: Player }) { return <div className={`initiative ${player.hasInitiative ? 'held' : ''}`} title={player.hasInitiative ? 'Ima inicijativu' : 'Bez inicijative'}><div><Crosshair size={23} /></div><span>INICIJATIVA</span><small>{player.hasInitiative ? game.initiativeClaimed ? 'PREUZETA' : 'TVOJA' : '—'}</small></div>; }
function Arena({ name, kind, enemyCards, friendlyCards, cardAction, onCard, inspect, busy, attackerId }: { name: string; kind: string; enemyCards: Card[]; friendlyCards: Card[]; cardAction: (c: Card) => GameAction | undefined; onCard: (c: Card) => void; inspect: (c: Card) => void; busy: boolean; attackerId?: string }) {
  return <section className={`arena arena-${kind}`} aria-label={name}><div className="arena-label">{kind === 'ground' ? <Target size={14} /> : <Orbit size={15} />}<span>{name}</span><small>{enemyCards.length + friendlyCards.length} JEDINICA</small></div><div className="arena-side enemy-arena">{enemyCards.map(card => <GameCard key={card.uuid} card={card} canAct={!!cardAction(card)} onClick={() => onCard(card)} inspect={() => inspect(card)} busy={busy} enemy attacking={attackerId === card.uuid} />)}{!enemyCards.length && <div className="arena-empty"><span /><small>PROTIVNIČKI SEKTOR</small><span /></div>}</div><div className="arena-midline"><i /><span>{kind === 'ground' ? 'GROUND' : 'SPACE'}</span><i /></div><div className="arena-side friendly-arena">{friendlyCards.map(card => <GameCard key={card.uuid} card={card} canAct={!!cardAction(card)} onClick={() => onCard(card)} inspect={() => inspect(card)} busy={busy} attacking={attackerId === card.uuid} />)}{!friendlyCards.length && <div className="arena-empty"><span /><small>TVOJ SEKTOR</small><span /></div>}</div></section>;
}
function GameCard({ card, canAct, onClick, inspect, busy, mode = 'unit', enemy = false, attacking = false }: { card: Card; canAct: boolean; onClick: () => void; inspect: () => void; busy: boolean; mode?: 'unit' | 'hand'; enemy?: boolean; attacking?: boolean }) {
  return <div className={`game-card ${mode === 'hand' ? 'hand-card' : 'unit-card'} ${canAct ? 'is-legal' : ''} ${card.selected ? 'is-selected' : ''} ${card.exhausted ? 'is-exhausted' : ''} ${enemy ? 'enemy-card' : ''} ${attacking ? 'is-attacking' : ''}`}><button className="game-card-click" data-card-id={card.uuid} onClick={onClick} disabled={busy} aria-label={`${card.name}${canAct ? ', dostupna akcija' : ', detalji karte'}${card.selected ? ', odabrana' : ''}`} aria-pressed={card.selected || undefined}><CardImage card={card} decorative /><span className="game-card-shade" /><span className="card-cost">{card.cost ?? '•'}</span>{card.selected && <span className="card-selected-badge"><Check size={15} /></span>}{card.exhausted && <span className="exhausted-badge"><RotateCcw size={11} /> ISCRPLJENO</span>}<span className="game-card-name">{card.name}</span>{mode === 'unit' && <span className="unit-stats"><span className="stat-power"><Swords size={12} />{card.power ?? 0}</span>{(card.damage || 0) > 0 && <span className="stat-damage">−{card.damage}</span>}<span className="stat-health"><Shield size={12} />{card.remainingHp ?? card.hp ?? 0}</span></span>}</button><IconButton className="card-inspect" label={`Pregledaj kartu ${card.name}`} onClick={inspect}><Maximize2 size={13} /></IconButton>{!!card.upgrades?.length && <span className="upgrade-badge"><ArrowUpRight size={11} /> {card.upgrades.length}</span>}{!!card.captured?.length && <span className="capture-badge">{card.captured.length} zarobljeno</span>}</div>;
}

function PromptPanel({ game, busy, act, cards, inspect }: { game: GameView; busy: boolean; act: (action: GameAction) => Promise<void>; cards: Card[]; inspect: (card: Card) => void }) {
  const prompt = game.prompt; const [number, setNumber] = useState('0'); const [dropdown, setDropdown] = useState(''); const [distribution, setDistribution] = useState<Record<string, number>>({});
  useEffect(() => { setNumber(String(prompt?.number?.min ?? 0)); setDropdown(prompt?.dropdown?.[0] || ''); setDistribution({}); }, [prompt?.id, prompt?.number?.min, prompt?.dropdown?.join('|')]);
  if (!prompt) return null;
  const targetCards = cards.filter((card, i, arr) => !card.hidden && prompt.selectableCardIds.includes(card.uuid) && arr.findIndex(c => c.uuid === card.uuid) === i);
  const count = Object.values(distribution).reduce((a, b) => a + b, 0); const d = prompt.distribution;
  const targetCount = Object.values(distribution).filter(value => value > 0).length;
  const validDistribution = !!d && (count === 0 ? !!d.canChooseNoTargets : (d.canDistributeLess ? count <= d.amount : count === d.amount) && (!d.maxTargets || targetCount <= d.maxTargets));
  const buttonAction = (button: PromptButton): GameAction => game.legalActions.find(action => action.type === 'button' && action.arg === button.arg) || { type: 'button', arg: button.arg, method: button.command || 'menuButton', promptId: prompt.id, label: button.text };
  const buttons = (prompt.buttons || []).filter(button => button.command !== 'statefulPromptResults' && !(prompt.number && /^\d+$/.test(button.arg)) && !(prompt.dropdown?.includes(button.arg)));
  const submitDistribution = () => { if (d) void act({ type: 'stateful', promptId: prompt.id, result: { type: d.type, valueDistribution: Object.entries(distribution).filter(([, amount]) => amount > 0).map(([uuid, amount]) => ({ uuid, amount })) } }); };
  const displayCardAction = (card: Card & { cardUuid?: string }): GameAction | undefined => game.legalActions.find(a => a.type === 'card' && a.cardId === (card.uuid || card.cardUuid)) || game.legalActions.find(a => a.type === 'button' && a.arg === (card.uuid || card.cardUuid));
  const finished = game.winnerIds?.length > 0;
  return <section className={`prompt-panel ${prompt.active ? 'prompt-active' : ''} ${busy ? 'prompt-busy' : ''}`} aria-label="Naredbe" aria-busy={busy}><div className="prompt-main"><div className="prompt-symbol">{busy ? <LoaderCircle className="spin" size={21} /> : finished ? <Flag size={21} /> : <Crosshair size={21} />}</div><div className="prompt-copy"><span className="eyebrow">{finished ? 'KRAJ PARTIJE' : busy ? 'OBRADA NAREDBE' : prompt.active ? 'TVOJ POTEZ' : 'SUSTAV IGRE'}</span><h3>{finished ? 'Partija je završena.' : translate(prompt.title) || 'Čekanje sljedeće akcije…'}</h3>{prompt.subtitle && <p>{translate(prompt.subtitle)}</p>}{prompt.selectableCardIds.length > 0 && !d && <small>{prompt.selectedCardIds.length > 0 ? `${prompt.selectedCardIds.length} odabrano · ` : ''}Odaberi označenu kartu{prompt.selectMode === 'multiple' ? ' ili više karata' : ''}.</small>}</div><div className="prompt-buttons">{buttons.map((button, i) => <button key={`${button.arg}-${i}`} className={/initiative/i.test(button.text) ? 'initiative-button' : /done|keep|yes|confirm/i.test(button.arg + button.text) ? 'primary-button small-button' : 'secondary-button small-button'} disabled={busy || button.disabled || finished} onClick={() => void act(buttonAction(button))}>{/initiative/i.test(button.text) && <Crosshair size={14} />}{translate(button.text)}</button>)}</div></div>
    {game.legalActions.some(action => action.type === 'card') && !d && <details className="target-action-list"><summary>Dostupni ciljevi i odabiri <ChevronDown size={12} /></summary><div>{game.legalActions.filter(action => action.type === 'card').map((action, i) => <button key={`${action.cardId}-${i}`} data-card-id={action.cardId} className="secondary-button small-button" disabled={busy || action.disabled} onClick={() => void act(action)}>{prompt.selectedCardIds.includes(action.cardId || '') && <Check size={13} />}{action.label || cards.find(card => card.uuid === action.cardId)?.name || 'Skrivena karta'}</button>)}</div></details>}
    {prompt.number && <div className="number-prompt"><label htmlFor="prompt-number">Odaberi broj ({prompt.number.min}–{prompt.number.max})</label><input id="prompt-number" type="number" min={prompt.number.min} max={prompt.number.max} value={number} onChange={e => setNumber(e.target.value)} /><button className="primary-button small-button" disabled={busy || !number || +number < prompt.number.min || +number > prompt.number.max || !Number.isInteger(+number)} onClick={() => void act({ type: 'button', arg: number, promptId: prompt.id })}>Potvrdi</button></div>}
    {!!prompt.dropdown?.length && <div className="number-prompt"><select aria-label="Odaberi opciju" value={dropdown} onChange={e => setDropdown(e.target.value)}>{prompt.dropdown.map(option => <option key={option}>{option}</option>)}</select><button className="primary-button small-button" disabled={busy} onClick={() => void act({ type: 'button', arg: dropdown, promptId: prompt.id })}>Potvrdi odabir</button></div>}
    {!!prompt.displayCards?.length && <div className="display-card-prompt">{prompt.displayCards.map((card, i) => { const action = displayCardAction(card); const perCard = game.legalActions.filter(a => a.type === 'perCard' && a.cardId === (card.uuid || card.cardUuid)); return <div key={card.uuid || card.cardUuid || i}><GameCard card={{ ...card, uuid: card.uuid || card.cardUuid || String(i), selected: card.selected || card.selectionState === 'selected' }} canAct={!!action} onClick={() => action ? void act(action) : inspect(card)} inspect={() => inspect(card)} busy={busy} mode="hand" />{card.displayText && <small>{card.displayText}</small>}{perCard.map((action, k) => <button key={k} className="secondary-button small-button" disabled={busy} onClick={() => void act(action)}>{translate(action.label)}</button>)}</div>; })}</div>}
    {d && <div className="distribution-prompt"><div className="distribution-heading"><span>Raspodijeli {d.type.toLowerCase().includes('healing') ? 'liječenje' : d.type.toLowerCase().includes('token') ? 'žetone' : 'štetu'}</span><strong>{count} / {d.amount}</strong></div>{targetCards.map(card => { const max = d.isIndirectDamage && !card.type?.includes('base') ? Math.min(d.amount, card.remainingHp ?? card.hp ?? d.amount) : d.amount; return <div className="distribution-target" key={card.uuid}><button className="text-button" onClick={() => inspect(card)}>{card.name}<Eye size={13} /></button><div><IconButton label={`Smanji za ${card.name}`} onClick={() => setDistribution(old => ({ ...old, [card.uuid]: Math.max(0, (old[card.uuid] || 0) - 1) }))} disabled={busy || !distribution[card.uuid]}><Minus size={14} /></IconButton><input type="number" aria-label={`Količina za ${card.name}`} min="0" max={max} value={distribution[card.uuid] || 0} onChange={e => setDistribution(old => ({ ...old, [card.uuid]: Math.min(max, Math.max(0, Math.floor(Number(e.target.value) || 0))) }))} /><IconButton label={`Povećaj za ${card.name}`} onClick={() => setDistribution(old => ({ ...old, [card.uuid]: Math.min(max, (old[card.uuid] || 0) + 1) }))} disabled={busy || (distribution[card.uuid] || 0) >= max || count >= d.amount}><Plus size={14} /></IconButton></div></div>; })}<div className="distribution-footer"><small>{d.maxTargets ? `Najviše ${d.maxTargets} ciljeva. ` : ''}{d.canDistributeLess ? 'Možeš raspodijeliti manje od ukupne količine.' : 'Raspodijeli ukupnu količinu.'}</small><button className="primary-button small-button" disabled={busy || !validDistribution} onClick={submitDistribution}>Potvrdi raspodjelu <Check size={15} /></button></div></div>}
    {!!game.warnings?.length && <div className="game-warnings">{game.warnings.map((warning, i) => <p key={i}><CircleHelp size={14} />{warning}</p>)}</div>}
  </section>;
}

function TokenControls({ game, busy, act, inspect }: { game: GameView; busy: boolean; act: (action: GameAction) => Promise<void>; inspect: (card: Card) => void }) {
  const players = Object.values(game.players).filter(player => player.forceToken?.active || player.credits?.length);
  if (!players.length) return null;
  return <div className="token-controls">{players.map(player => <div key={player.id}><span className="eyebrow">{player.id === 'human' ? 'TVOJI ŽETONI' : 'PROTIVNIČKI ŽETONI'}</span>{player.forceToken?.active && <button data-card-id={player.forceToken?.uuid} className={`token-button ${game.legalActions.some(action => action.cardId === player.forceToken?.uuid) ? 'is-legal' : ''}`} disabled={busy || !game.legalActions.some(action => action.cardId === player.forceToken?.uuid)} onClick={() => { const action = game.legalActions.find(action => action.cardId === player.forceToken?.uuid); if (action) void act(action); }}><Orbit size={15} /> Sila</button>}{player.credits?.map(card => <button data-card-id={card.uuid} className={`token-button ${game.legalActions.some(action => action.cardId === card.uuid) ? 'is-legal' : ''}`} disabled={busy} key={card.uuid} onClick={() => { const action = game.legalActions.find(action => action.cardId === card.uuid); if (action) void act(action); else if (!card.hidden) inspect(card); }}><Zap size={14} />{card.name || 'Kredit'}</button>)}</div>)}</div>;
}

function RulesContent({ openSources, version }: { openSources: () => void; version: string }) {
  return <div className="modal-body rules-content"><div className="rules-intro"><Crosshair size={32} /><div><h3>Tvoja misija: uništi protivničku bazu.</h3><p>Sustav obrađuje troškove, dopuštene ciljeve, okidače i učinke. Ti donosiš odluke.</p></div></div><div className="rules-grid"><article><span>01 / PRIPREMA</span><h3>Odaberi resurse</h3><p>Počinješ sa šest karata. Možeš jednom zamijeniti cijelu početnu ruku. Zatim odaberi dvije karte iz ruke koje postaju resursi.</p></article><article><span>02 / AKCIJSKA FAZA</span><h3>Jedna akcija naizmjence</h3><p>Odigraj kartu, napadni spremnom jedinicom, upotrijebi sposobnost ili preuzmi inicijativu. Označene karte imaju dostupnu akciju ili su dopušteni ciljevi.</p></article><article><span>03 / BORBA</span><h3>Dvije zasebne arene</h3><p>Kopnene jedinice napadaju u kopnenoj areni, svemirske u svemirskoj. Obje mogu napasti bazu. Jedinice istodobno nanose štetu, osim kada učinak karte kaže drukčije.</p></article><article><span>04 / NOVA RUNDA</span><h3>Regrupiranje</h3><p>Izvuci dvije karte, po želji pretvori jednu kartu iz ruke u resurs i pripremi iscrpljene karte. Igrač s inicijativom započinje sljedeću rundu.</p></article></div><div className="rules-tips"><h3>Komande na bojištu</h3><p><span className="example-outline" /> Označena karta — klikni za akciju ili odabir cilja.</p><p><Maximize2 size={15} /> Povećalo — otvori sliku, tekst i stanje karte.</p><p><Check size={15} /> Kod višestrukog odabira označi karte, zatim potvrdi.</p><p><Crosshair size={15} /> Preuzimanje inicijative završava tvoje akcije za ovu fazu.</p></div><div className="notice"><BookOpen size={18} /><span>Tekst na kartama može promijeniti osnovna pravila. Izvorni nazivi i tekst sposobnosti ostaju na engleskom radi preciznosti.{version ? ` Referenca: ${version}.` : ''}</span></div><button className="secondary-button" onClick={openSources}>Službena pravila, errata i izvori <ExternalLink size={16} /></button></div>;
}
